[platformio]
src_dir = imu_spi  ; 這裡輸入你今天想編譯的資料夾名稱

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = mbed
monitor_speed = 115200
board_build.mbed.custom_mbed_app_json = ${platformio.src_dir}/mbed_app.json
build_flags = -Wl,-u,_printf_float,-u,_scanf_float